### ISSUE TITLE
When launching psql for the first time, it pulls postgres:latest docker image!

### ISSUE THREAD

**Issue by seb-elico** [ajite/docker-postgres-client#1]
$ psql
Error: No such image or container: containers_postgres_1
Unable to find image 'postgres:latest' locally
Pulling repository postgres

I'm not using postgres:latest on this server. I'm not a big fan of this default behavior that tries to connect to a default container. But why does it try to pull postgres:latest image?

**Comment by seb-elico** [comment]
I think it's related: when I try to connect to my postgres container, it tries to pull postgres:9.4 (which I indeed don't have on my server since I run postgres from an image that is a clone of postgres:9.4 that I pulled from my private repository)

**Comment by ajite** [comment]
Hi Sebastien,

Thank you for your feedback. I changed the code to make it work with unofficial Postgres images.

**Comment by ajite** [comment]
Hi Sebastien,

Thank you for your feedback. I changed the code to make it work with unofficial Postgres images.
